---
Title: 行为准则
---

== SuiteCRM 社区行为准则

我们理解，为了拥有一个健康、包容的社区，需要创建并鼓励一个积极的环境，以使成员能够感受到欢迎和安全感、相互学习并从平台中受益。我们的 SuiteCRM 社区由最终用户、系统管理员、开发人员，合作伙伴、员工以及那些提供 SuiteCRM 相关服务的人员组成，因此我们所有人都必须参与其中以确保社区的成功和福祉。

. **关爱他人**。善待他人并乐于助人。我们的社区欢迎和支持各种背景和身份的人，他们应受到专业的尊重。不尊重以及不可接受的行为包括但不限于：

.. 使用淫秽性的语言或意象以及不受欢迎的性骚扰或性侵犯行为
        
.. 引战、侮辱性/贬损性评论，以及人身或政治攻击
        
.. 公开或私下骚扰
        
.. 未经明确许可发布他人的私人信息，例如现实中的地址或电子地址
        
. **保持客观**。我们在这里主要讨论的是技术问题：情绪是与生俱来的，但请记住，负面情绪不能解决技术问题。请（事先）假设他人的意图是最好的。
    
. **有责任心**。确保你的行为的结果是为了项目和社区的利益。尊重安全最佳实践，并致力于实现可靠、可维护的解决方案。如果你知道任何有关 SuiteCRM 的安全问题，你可以发邮件到 mailto:security@suitecrm.com[security@suitecrm.com]。
    
. **帮助人们学习**。我们欢迎所有知识水平的人。一开始不了解 SuiteCRM 的基本功能或不知道如何寻找解决方案是很正常的，我们都经历过。
    
. **别发垃圾信息**。这是一个开源社区，而非市场。不要推销你的服务或产品。如果你是合作伙伴、扩展开发人员或专门为 SuiteCRM 提供开发或咨询服务的人，那么您可以告知其他人并回应请求。但是，我们不允许仅仅做广告而无实质内容，否则你的帖子将被视为垃圾内容。
    
. **尽己所能**。在提问之前，请阅读文档并搜索所有指南或建议，以节省其他人的时间。
    
. **耐心一点**。很多人或公司参与了社区事务，他们是自愿为该项目付出时间和精力的。所以你的问题、代码贡献或建议可能无法立即得到回复。给别人一点时间，成为一个好的贡献者以赢得他人的关注，而非固执己见。
    
. **不要一味索取，还得给予**。开源的一个原则是参与，因此在我们社区中很多事情能做到免费都是出于他人的善意，请互帮互助。你可以参与许多不同的方式来作贡献：代码、支持、文档、测试、翻译、推广……
    

  
  

我们保留删除任何不遵守这些准则的帖子或封禁任何一再违反这些准则的人的权利。

本准则既适用于项目空间，也适用于当个人代表项目或其社区时的公共空间。个人代表项目或社区的例子包括使用官方项目电子邮件地址、参与项目论坛，通过官方社交媒体帐户发布信息或在线上或线下活动中充当指定代表。

如遇到虐待、骚扰或其他不可接受的行为，可联系项目组邮箱 mailto:community@suitecrm.com[community@suitecrm.com]。我们将审阅和调查所有投诉，并作出必要和适当的回应。项目组有义务将事件的举报人保密。具体执行政策的进一步详情会另行公布。

这些指南改编自网站 http://contributor-covenant.org/[Contributor Covenant]，版本 1.4，参见 http://contributor-covenant.org/version/1/4/[此处]。


