---
title: 文档编写指南
weight: 50
---

:toc:

要充分解释如何在我们的文档文件中工作，你得熟悉 Hugo（我们的渲染引擎）、学习（我们的 Hugo 主题）和 Asciidoc（我们使用的标记样式）。

下面的解释只是一些常用语法的简短列表，以及一些关于命名约定和我们遵循的其他规则的建议，这些都出于一致性和其他实际原因。

== 文件在路径中的位置

通常你要编辑的文件都位于 `content` 目录下，在这里你能找到文档指南的主要章节：*用户*, *开发者*、*管理员*、*社区* 和 *技术博客*。

你可以在其中为子章节创建新目录，还可以创建新文件。你应该了解 link:https://gohugo.io/content-management/organization/[Hugo 使用目录和文件位置] 生成内容的方式。我们目前并没有用到 Hugo 的 *Page Bundles*，但我们计划将来使用它们。

== 命名文件

对于目录名和文件名，我们都使用页面标题来表示，因为它们出现在 front-matter 中，但仅使用小写字母，不可以出现空格或特殊字符。

基本上，我们正在尝试模仿 Hugo 在 `public` 目录下生成最终内容的方式，以使源代码与渲染后的内容之间不会出现太大差异。我们发现，这样做有助于内容的管理。

因此位于目录 `Installation Guide` 下的标题为 `Downloading & Installing` 的页面可以有这样的文件名：`installation-guide/downloading-installing.adoc`。

=== 命名翻译后的文件

对于翻译，我们保留英文文件名（这是 Hugo 辨别同一文件的不同翻译版本的方式），但在 `.adoc` 扩展名前加上国际语言代码。

所以这些是同一文件的所有翻译版本（英文、西班牙文、俄文）：

```
requirements.adoc
requirements.es.adoc
requirements.ru.adoc
```
请注意，我们本可以使用 `requirements.en.adoc` 作为英文版本的文件名，但我们并未那样做。我们不在默认语言（英文）上使用任何国际语言代码并会保持下去。

== Front-matter 和 Special Codes

每个 Asciidoc 内容文件都从一个被称为 *Front-matter* 的部分开始：

```
---
title: 文档编写指南
weight: 50
---
```
尽管有 link:https://gohugo.io/content-management/front-matter/[很多东西] 可以在这里定义，但我们只使用 `title` 和 `weight` 属性。 

`weight` 定义了目录中的位置，即页面所属部分的顺序。我们使用 10 作为 `weight` 的增量（步进），这样如果我们想在另外两个预先存在的页面之间插入一个新页面，那么就很容易找到一个可用的数字。所以我们把它们编号为 10、20、30 等，而非仅仅 1、2、3 等。 

一些 *Special Codes* 可以被用在文件的开头，紧随着 front-matter：

- 使用特别的图形外观绘制按钮：
```
:experimental:   ////这是为了允许在下面使用 btn:[] 语法

这是一条表示你可以在用户界面上按下 btn:[Save] 的示例语句。
```

- 设置将在整个文件中使用的图像基础目录（base directory）：
```
:imagesdir: /images/en/admin
```
对于图像，应将此目录指定为绝对路径（以 `/` 打头），而不是 `../../images` 之类的相对路径。请注意，这条指南仅适用于图像，不适用于指向页面的链接（页面链接应当是相对的）。

- 添加一个自动生成的文件内各部分（章节）的 *目录列表*：https://learn.netlify.com/en/shortcodes/children/
```
:toc:
```
- 添加一个自动生成的位于当前页面目录级别下方的页面的目录列表，以用于具有子目录的页面。（这是一个 shorcode：link:https://learn.netlify.com/en/shortcodes/children/[我们的主题^]）

```
{{%/* children depth="3" showhidden="true" */%}}
```
- 添加一个自动生成的 *GitHub 贡献者列表*（用于 *发行说明* 页面）。你可以列出数量不详的贡献者。（这是 link:https://github.com/salesagility/SuiteDocs/blob/master/layouts/shortcodes/ghcontributors.html[在我们自己的网站上定义的^] 一个短代码，如果你想创建其他的，它可以作为一个用来参照的例子。）
```
{{%/* ghcontributors username1 username2 */%}}
```

== 内容

在普通的文本内容中，我们遵循以下规则

- 大约在第 80 列处断行。Asciidoc 会忽视这些换行。我们这样用以便在典型的 80 字符宽的控制台上编辑源代码。

- 使用重音符包裹路径、文件名、变量名和其他表达式有助于复制粘贴：
 
```text
此源标记允许你便捷复制一个路径 `/some/path` 到编辑器中。
```

== 参考

- 使用普通的 Asciidoc 链接在文件中导航

- 对于页面，请尽可能使用相对链接。这对于翻译后的页面能够使用与英语页面相同的导航至关重要。因此，你的链接将如下所示：

```text
这是一个 link:../../admin/my-page.adoc[你要去点击的链接！]
```
尽量使用必须的最少数量的 `..`，当通过带 `..` 的目录回退时，千万不要跑到 `content` 目录上面，这毫无必要。

- 对于图像，如上面解释的那样使用 `:imagesdir:` 接着使用一个无路径的链接
