---
Title: "文档工作的本地配置"
Weight: 40
---

为了贡献文档，你确实可以直接在 GitHub 上编辑页面。不过如果你想要更强大的配置以便拥有更好的工作体验，你可以配置一个文件项目的本地副本，安装我们使用的构建引擎 Hugo，然后构建并在本地运行文档站点。

{{% notice 警告 %}}
这是一种编辑文档的高级方法，它只应适用于那些具备必要技术能力并希望广泛参与文档工作的人员。 
{{% /notice %}}

== 在你的计算机上安装必需的软件

我们需要运行以下安装包：

- Git（版本控制）
- Asciidoctor（处理 Asciidoc 标记）
- Hugo（静态网站引擎）

{{% notice 提示 %}}
下面的说明是针对 Ubuntu 64 位的，但应该很容易地适用于其他的 Linux 和 MacOS 系统。Windows 上的安装也是的。 有关其他安装环境的具体说明，请参阅本文底部的链接。
{{% /notice %}}

`sudo apt-get update`

`sudo apt-get install git`

这行命令可以方面地下载最新版本的 Hugo：

[source, bash]
wget https://github.com`wget -qO- https://github.com/gohugoio/hugo/releases/latest | grep -oE -m 1 '\/gohugoio\/hugo\/releases\/download\/v[0-9]+.[0-9]+.[0-9]*\/hugo_[0-9]+.[0-9]+.[0-9]*_Linux-64bit.deb'`

要是上面的命令没用，使用以下命令可以达到类似的效果，只需把 `0.53` 替换成最新的版本号： 
`wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb`

此时安装刚刚下载的包文件，如果当前文件目录下只有这一个，你可以这样做：

`sudo dpkg -i hugo*.deb`

现在检查 Hugo 的版本 

`hugo version`

转到某些适当的目录，然后使用以下命令来创建 SuiteDocs 文件目录树并下载所有内容：

`git clone https://github.com/salesagility/SuiteDocs.git`

`cd SuiteDocs`

`bundle install`

这会在本地创建 Gemfile 并请求 "asciidoctor" 依赖包，安装它然后检查版本：

`asciidoctor --version`

== 开始运行本地站点

已经就绪了！要构建站点，你可以键入 

`hugo`

不过你不会常用到它，因为这足以启动本地的 web 服务器。其他未完成的更改都将使用以下命令进行重建：

`hugo server --bind=0.0.0.0 --baseUrl=http://10.0.0.200 --navigateToChanged --enableGitInfo`

注意将 `10.0.0.200` 改成任意的本地 IP 地址。

这就是你要键入到浏览器地址栏中的 URL 以浏览本地站点。

在进行内容上的工作时，我们建议保持第二个终端窗口为常开状态始终运行服务器，以便你可以检查所有的错误消息，以及查看服务器（如何）自动地处理你的编辑内容并重新部署。

== 优点

除了通过 GitHub 在内容上进行协作的优点之外，这种本地设置还允许你就内容结合使用 Linux 的全部功能，比如 `grep`、`bash`、`php`... 大规模的操作既快速又简单。 

快速、自动的重新部署，以及对更改内容的自动浏览器导航，在编辑内容时非常方便。 

最后，整个站点都可以进行编辑：不仅仅是文本内容，还有视觉方面、功能等等。你可以用 Golang 编码一个新站点，这也是贡献。

== 有用的链接

https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[安装 Git^]

https://gohugo.io/getting-started/installing/[安装 Hugo^]

https://asciidoctor.org/docs/install-toolchain/[安装 Asciidoctor^]
